# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

defaults: &defaults
  macos:
    xcode: "10.1.0"
  working_directory: ~/repo

version: 2
jobs:
  build_and_test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore node modules
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          name: Save node modules
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build Apps
          command: yarn build

  releaseVersion:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore node modules
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          name: Save node modules
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install Wine & RPM
          command: brew install wine && brew install rpm
      - run:
          name: Decode Certificates
          command: base64 -D -o Certificates.p12 <<< $ReactotronCerts
      - run:
          name: Install Gems
          command: bundle install
      - run:
          name: Install Cert
          command: bundle exec fastlane setup
      - run:
          name: Run Release
          command: yarn ci:publish

workflows:
  version: 2
  test_and_release:
    jobs:
      - build_and_test:
          filters:
            branches:
                ignore:
                  - master
                  - beta
      - releaseVersion:
          context: ReactotronCerts
          filters:
            branches:
                only:
                  - master
                  - beta
